<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBAGAmvg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBAGAmvg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBAGAmvg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBAGAmvg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBAGAmvg\App_KernelDevDebugContainer([
    'container.build_hash' => 'BAGAmvg',
    'container.build_id' => '6c4eba55',
    'container.build_time' => 1733265203,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBAGAmvg');
