<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXWcrLKA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXWcrLKA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXWcrLKA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXWcrLKA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXWcrLKA\App_KernelDevDebugContainer([
    'container.build_hash' => 'XWcrLKA',
    'container.build_id' => 'df3e6345',
    'container.build_time' => 1733056210,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXWcrLKA');
